name: interhand
channels:
  - pytorch
  - pytorch3d
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - pip=22.1.2
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - torchaudio=0.11.0
  - pytorch3d=0.7.2
  - ffmpeg=4.3
  - ninja
  - pip:
      - numpy==1.23.5
      - pytorch-lightning==1.6.5
      - torchmetrics==0.11.0
      - test-tube==0.7.5
      - tensorboard==2.10.1
      - tensorboardX==2.5
      - diffusers==0.21.4
      - huggingface-hub==0.19.4
      - transformers==4.33.0
      - safetensors==0.3.3
      - opencv-python==4.6.0.66
      - opencv-python-headless==4.6.0.66
      - omegaconf==2.0.6
      - hydra-core==1.0.7
      - antlr4-python3-runtime==4.8
      - trimesh==3.12.3
      - pyrender==0.1.45
      - open3d==0.17.0
      - lpips==0.1.4
      - kornia==0.6.9
      - scikit-image==0.19.3
      - imageio==2.19.2
      - einops==0.5.0
      - smplx==0.1.28
      - chumpy==0.70
      - pycocotools==2.0.4
      - open-clip-torch==2.0.2
      - spconv-cu113==2.3.5
      - cumm-cu113==0.4.8
      - --find-links https://data.pyg.org/whl/torch-1.11.0+cu113.html
      - torch-scatter==2.0.9
      - fvcore==0.1.5.post20220512
      - iopath==0.1.9
      - openmesh==1.2.1
      - plyfile==0.9
      - rembg==2.0.30
      - matplotlib==3.5.2
      - pandas==1.4.3
      - scipy==1.9.1
      - tqdm==4.64.1
      - pyyaml==6.0
      - Pillow==9.2.0
      - git+https://github.com/facebookresearch/segment-anything.git
