# CUDA_VISIBLE_DEVICES='1,3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4_sam01.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10_sam01.json --num_gpu 2
# CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4_sam01.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10_sam01.json --run_val

# CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_pt_wild.json --run_val


# CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4_n34.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10_n34.json --num_gpu 1
# CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4_n34.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10_n34.json --run_val


CUDA_VISIBLE_DEVICES='0,1,2' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_x_50_ours_1_0.json --num_gpu 3
CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_x_50_ours_1_0.json --run_val

CUDA_VISIBLE_DEVICES='0,1,2' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_x_50_ours_1_2.json --num_gpu 3
CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_x_50_ours_1_2.json --run_val

CUDA_VISIBLE_DEVICES='0,1,2' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_x_50_ours_5_1.json --num_gpu 3
CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_x_50_ours_5_1.json --run_val

CUDA_VISIBLE_DEVICES='0,1,2' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_x_50_ours_5_3.json --num_gpu 3
CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_x_50_ours_5_3.json --run_val

CUDA_VISIBLE_DEVICES='0,1,2' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_x_50_ours_6_4.json --num_gpu 3
CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_x_50_ours_6_4.json --run_val









# CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand /home/huangx/TriplaneGaussian_online/online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c17_x_50_tw_tsp10_interhand_test.json --run_val

# ps aux | grep python

# CUDA_VISIBLE_DEVICES='2,3,0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c5_x_50_tw_tsp10.json --num_gpu 3
# CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10.json --run_val
# CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c5_x_50_tw_tsp10.json --run_val
# CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c6_x_50_tw_tsp10.json --run_val
# CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c7_x_50_tw_tsp10.json --run_val
# CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c8_x_50_tw_tsp10.json --run_val
# CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c9_x_50_tw_tsp10.json --run_val
# CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c10_x_50_tw_tsp10.json --run_val
# CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10.json --run_val
# CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10.json --run_val

# CUDA_VISIBLE_DEVICES='0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10.json --run_val --model_ckpt /home/huangx/TriplaneGaussian_online/EXPERIMENTS/online_shade_mano_pose_wild_time_texture_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_capture0_lr_c4_x_50_tw_tsp10_3/ckpts/last.ckpt



# CUDA_VISIBLE_DEVICES='2,3,0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c6_x_50_tw_tsp10.json --num_gpu 3
# CUDA_VISIBLE_DEVICES='2' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c6_x_50_tw_tsp10.json --run_val



# CUDA_VISIBLE_DEVICES='2,3,0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c9_x_50_tw_tsp10.json --num_gpu 3
# CUDA_VISIBLE_DEVICES='2' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c9_x_50_tw_tsp10.json --run_val




# CUDA_VISIBLE_DEVICES='2,3,0' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c10_x_50_tw_tsp10.json --num_gpu 3
# CUDA_VISIBLE_DEVICES='2' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c10_x_50_tw_tsp10.json --run_val


# CUDA_VISIBLE_DEVICES='2,3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10_1.json --num_gpu 2
# CUDA_VISIBLE_DEVICES='2' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10_1.json --run_val

# CUDA_VISIBLE_DEVICES='2,3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10_2.json --num_gpu 2
# CUDA_VISIBLE_DEVICES='2' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10_2.json --run_val

# CUDA_VISIBLE_DEVICES='2,3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10_3.json --num_gpu 2
# CUDA_VISIBLE_DEVICES='2' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10_3.json --run_val

# CUDA_VISIBLE_DEVICES='2,3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10_npt.json --num_gpu 2
# CUDA_VISIBLE_DEVICES='2' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10_npt.json --run_val


# CUDA_VISIBLE_DEVICES='2,3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c8_x_50_tw_tsp10.json --num_gpu 2
# CUDA_VISIBLE_DEVICES='2' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_nt_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c8_x_50_tw_tsp10.json --run_val


# #ab2
# CUDA_VISIBLE_DEVICES='3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr3.py --config online_shade_mano_pose_wild_time_tex_fenli_nt.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c7_x_50_ab2.json
# CUDA_VISIBLE_DEVICES='3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr3.py --config online_shade_mano_pose_wild_time_tex_fenli_nt.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c7_x_50_ab2.json --run_val


# CUDA_VISIBLE_DEVICES='3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr3.py --config online_shade_mano_pose_wild_time_tex_fenli_nt.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c8_x_50_ab2.json
# CUDA_VISIBLE_DEVICES='3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr3.py --config online_shade_mano_pose_wild_time_tex_fenli_nt.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c8_x_50_ab2.json --run_val


# CUDA_VISIBLE_DEVICES='3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr3.py --config online_shade_mano_pose_wild_time_tex_fenli_nt.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_ab2.json
# CUDA_VISIBLE_DEVICES='3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr3.py --config online_shade_mano_pose_wild_time_tex_fenli_nt.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_ab2.json --run_val


# CUDA_VISIBLE_DEVICES='3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr3.py --config online_shade_mano_pose_wild_time_tex_fenli_nt.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c6_x_50_ab2.json
# CUDA_VISIBLE_DEVICES='3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr3.py --config online_shade_mano_pose_wild_time_tex_fenli_nt.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c6_x_50_ab2.json --run_val


# CUDA_VISIBLE_DEVICES='3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr3.py --config online_shade_mano_pose_wild_time_tex_fenli_nt.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c9_x_50_ab2.json
# CUDA_VISIBLE_DEVICES='3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr3.py --config online_shade_mano_pose_wild_time_tex_fenli_nt.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c9_x_50_ab2.json --run_val

# CUDA_VISIBLE_DEVICES='3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr3.py --config online_shade_mano_pose_wild_time_tex_fenli_nt.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c10_x_50_ab2.json
# CUDA_VISIBLE_DEVICES='3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr3.py --config online_shade_mano_pose_wild_time_tex_fenli_nt.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c10_x_50_ab2.json --run_val



# CUDA_VISIBLE_DEVICES='3' python infer_hand_train_shade_mano_pose_wild_4d_fenli_loss_mano_lmask_t_reg_sym_sam1_pt_lr4.py --config online_shade_mano_pose_wild_time_tex_fenli_t_reg_tsp10.yaml --config_hand online_shade_mano_pose_wild_time_tex_4d_fenli_loss_mano_sam_res_lmask_magic_t_reg_sym_res1_sam1_vtreg_lr_c4_x_50_tw_tsp10_.json